spring:
  application:
    name: gateway
    
zuul:  routes:
    # requests with context matching /hello/** will be routed to hello-service    hello-service: /hello/**
    book-service: /books/**